matrix:
  include:
    - language: scala
      scala: 2.13.1

      script:
        - cd ci; sbt clean coverage test coverageReport

      after_success:
        - bash <(curl -s https://codecov.io/bash)
